AllCops:
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'fakeit.gemspec'

Security/Open:
  Enabled: false
