AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'fakeit.gemspec'

Security/Open:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/MethodLength:
  Max: 20
